name: Release Tarball

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  php-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress
      - name: Generate Composer Autoload Files
        run: composer dump-autoload
      - name: Run PHP Unit Tests
        run: make php-test

  js-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install NPM dependencies
        run: npm ci
      - name: Run TypeScript Tests
        run: make js-test 

  release:
    runs-on: ubuntu-latest
    needs: [php-tests, js-tests]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress
      - name: Install NPM dependencies
        run: npm ci
      - name: Build tarball
        run: make tarball
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/project.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 